config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :signout
  end

  resources :users, only: %i[ show edit update ]
  resources :tasks
  
  root "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true
  validates :status, presence: true, inclusion: { in: ['new', 'in-progress', 'done'] }
  validates :user, presence: true

  STATUS_OPTIONS = [
    ['new', 'new'],
    ['in progress', 'in-progress'],
    ['done', 'done']
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
  
  validates :first_name, length: {maximum: 35}
  validates :last_name, length: {maximum: 35}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_user_can_edit?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation]
    )
    devise_parameter_sanitizer.permit(
      :account_update, keys: [:password, :password_confirmation, :current_password]
    )
  end

  def current_user_can_edit?(task)
    user_signed_in? && task.user == current_user
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: %i[ show, index]
  before_action :set_task, only: %i[ show ]
  before_action :set_current_user_task, only: %i[ edit, update, destroy]

  # GET /tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to @task, notice: "Task was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: "Task was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: "Task was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :status)
    end

    def set_current_user_task
      @task = current_user.tasks.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update ]
  before_action :authenticate_user!
  before_action :set_current_user, except: %i[ show ]

  # GET /users/1
  def show
    @user
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:id].nil?
        @user = current_user
      else
        @user = User.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end

    def set_current_user
      @user = current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def display_errors_for(object)
  #   return unless object.errors.any?
  #   render partial: "partials/form_errors", 
  #          locals: { object: object }
  # end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>  

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <%= link_to "Project app", root_path, class: 'navbar-brand' %>

        <div class="navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Account", current_user %></li>
              <li><%= link_to "Edit", edit_user_path(current_user)  %></li>
              <li><%= link_to "Sign out", destroy_user_session_path %></li>
            <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
        <div class="col-lg-3">

        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Project app 2022</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/partials/_form_errors.html.erb
<% errors = model.errors %>  

<% if errors.any? %>
  <div class="alert alert-danger">
    <div class="lead buffer-bottom">
      <h2>Please fix <%= pluralize(errors.count, "error") %></h2>
    </div>

    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %> 

app/views/tasks/_form.html.erb
<%= form_with(model: @task) do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <p><%= f.select :status, Task::STATUS_OPTIONS, class: 'form-control' %></p>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %> or <%= link_to 'back', :back %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <%= content_tag 'div', '' %>

    <div class="thumbnail-inner task-info-inner">
      <div class="caption">
        <div class="task-description">
          <h3><%= link_to task.title, task_path(task) %></h3>
          <h3><small><%= task.status %></small></h3>
          <div class="buffer-both"><%= task.description %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<div class="buffer-both">
  <%= link_to 'Create new', new_task_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%= render partial: 'tasks/task', collection: @tasks %>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="task">
  <div class="task-info row">
    <div class="col-md-12">

      <div class="task-info-inner row">
        <div class="col-md-6">
          <div class="task-description">
            <h1><%= @task.title %></h1>
            <h1><%= @task.status %></h1>
            <p><%= @task.description %></p>
          </div>

          <% if current_user_can_edit?(@task) %>
            <div class="buffer-both">
              <%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-primary' %>
            </div>
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |f| %>
  <%= render partial: "partials/form_errors", locals: {model: @user} %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :flast_name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %> or <%= link_to 'back', :back %>
  </div>

<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Account settings</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>

    <p class="buffer-top">
      <%= link_to 'Update password', edit_user_registration_path %>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div>
  <h1><%= @user.first_name %></h1>
  
  <div class="task-info row">
    <div class="col-md-12">
      <% if @user.tasks.any? %>
        <h3>Tasks:</h3>
        <div class="column">
          <%= render partial: 'tasks/task', collection: @user.tasks %>
        </div>
      <% else %>
        <p class="">Yay! No tasks assigned!</p>
      <% end %>
    </div>
    
    <% if @user == current_user %>
      <p class=""><%= link_to "Edit account details", edit_user_path(@user), class: "btn-light" %></p>
    <% end %>
  </div>
</div>